Add tests, fix caulking and remove whitelists

diff --git a/pre-commit.d/cloud-gov-caulking b/pre-commit.d/cloud-gov-caulking
--- a/pre-commit.d/cloud-gov-caulking
+++ b/pre-commit.d/cloud-gov-caulking
@@ -1,11 +1,7 @@
 #!/usr/bin/env bash
 
-config="$HOME/src/github.com/cloud-gov/caulking/leaky-repo.toml"
-
-if [[ ! -f "$config" ]]; then
-  echo "caulking: Cannot find $config - continuing without running gitleaks"
-  exit 0
-fi
+stock_config="$HOME/src/github.com/cloud-gov/caulking/leaky-repo.toml"
+local_config="$HOME/src/github.com/cloud-gov/caulking/local.toml"
 
 if [[ "$(git config --bool hooks.gitleaks)" != "true" ]]; then
   # shellcheck disable=SC2016
@@ -13,7 +9,17 @@ if [[ "$(git config --bool hooks.gitleaks)" != "true" ]]; then
   exit 0
 fi
 
-if ! output=$(gitleaks --verbose --pretty --config="$config" 2>&1); then
+if [[ ! -f "$stock_config" ]]; then
+  echo "caulking: Cannot find $stock_config - continuing without running gitleaks"
+  exit 0
+fi
+
+if [[ ! -f "$local_config" ]]; then
+  echo "caulking: Cannot find $local_config - continuing without running gitleaks"
+  exit 0
+fi
+
+if ! output=$(gitleaks --verbose --pretty --config=<(cat "$stock_config" "$local_config") 2>&1); then
   echo "$output" | sed 's/^.*\[[0-9:TZ-]\+\] //; s/^/caulking: /'
   cat <<-EOF
 		caulking:
